# Numpy数据存取与函数

* ### [一维和二维数据的存取](#point1)
  * ###### [CSV文件, np.loadtxt(), np.savetxt()](#point1_1)
* ### [多维数据的存取](#point2)
  * ###### [a.tofile(), np.fromfile()](#point2_1)
  * ###### [np.save(), np.load()](#point2_2)
* ### [numpy的随机函数(np.random)](#point3)
  * ###### [rand(), randn(), randint(), seed()](#point3_1)
  * ###### [shuffle(), permutation(), choice()](#point3_2)
  * ###### [uniform(), normal(), poisson()](#point3_3)
* ### [numpy的统计函数](#point4)
  * ###### [sum(), mean(), average(), std(), var()](#point4_1)
  * ###### [min(), max(), argmin(), argmax(), unravel_index(), ptp(), median()](#point4_2)
* ### [numpy的梯度函数](#point5)
  * ###### [np.gradient()](#point5_1)

<div id="point1"></div>
### CSV文件：存取一维和二维数据
* CSV文件是一种常见的文件格式，用来存储批量数据。
* CSV文件只能有效的存储一维和二维数组。
* np.savetxt(), np.loadtxt()只能有效的存取一维和二维数组。

<div id="point1_1"></div>
##### Numpy将数据存入CSV文件，函数如下：
<img src="images/6.png" align="left">

In [24]:
import numpy as np

In [25]:
a = np.arange(100).reshape(5, 20)
np.savetxt('a.csv', a, fmt="%d", delimiter=',')

<img src="images/7.png" align="left">

##### Numpy读入CSV文件，函数如下：
<img src="images/8.png" align="left">

In [26]:
b = np.loadtxt('a.csv', delimiter=',')
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [27]:
b = np.loadtxt('a.csv', dtype=np.int32, delimiter=',')
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

<div id="point2"></div>
### 多维数据的存取
* 数据存入:tofile，数据加载loadfile
* 便捷的文件存取方法：np.save，np.load

<div id="point2_1"></div>
##### 多维数据的存入：tofile函数
<img src="images/9.png" align="left">

In [28]:
a = np.arange(100).reshape(5, 10, 2)
a.tofile("b.dat", sep=",", format='%d')

结果将会平铺为一维数据，如下：
<img src="images/10.png" align="left">

##### 多维数据的加载：np.fromfile函数
<img src="images/11.png" align="left">

In [29]:
c = np.fromfile("b.dat", dtype=np.int32, sep=",")
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
# 要想还原数据，还要知道原先数组的尺寸
c = c.reshape(5, 10, 2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

<div id="point2_2"></div>
##### 便捷的文件存取：np.save，np.load
<img src="images/12.png" align="left">

In [31]:
a = np.arange(100).reshape(5, 10, 2)

In [32]:
np.save("a.npy", a)

In [33]:
b = np.load("a.npy")
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

##### 两种存取方法比较
<img src="images/13.png" align="left">

<div id="point3"></div>
### Numpy的随机数函数

<div id="point3_1"></div>
##### np.random的随机数函数（一）
<img src="images/14.png" align="left">

In [34]:
a = np.random.rand(3, 4, 5)
a

array([[[0.23898213, 0.27601163, 0.87723431, 0.01850997, 0.42801385],
        [0.84904551, 0.51869559, 0.60016379, 0.06652204, 0.31832621],
        [0.49211065, 0.26498793, 0.55268661, 0.24297381, 0.20056634],
        [0.05752046, 0.02083487, 0.90090356, 0.39565131, 0.17881736]],

       [[0.45368397, 0.16636612, 0.34729773, 0.66995526, 0.66284839],
        [0.69844071, 0.94089291, 0.8451882 , 0.22476632, 0.00510757],
        [0.28641425, 0.94772812, 0.27095787, 0.47314137, 0.04966217],
        [0.41073918, 0.14655958, 0.14239134, 0.3289339 , 0.8435859 ]],

       [[0.60749954, 0.45277439, 0.68472308, 0.05936392, 0.29091105],
        [0.3659686 , 0.36362643, 0.40661621, 0.38137314, 0.57751196],
        [0.43838137, 0.68232673, 0.33005561, 0.96497601, 0.06961315],
        [0.17180349, 0.48468977, 0.39673882, 0.93665498, 0.01728183]]])

In [35]:
sn = np.random.randn(3, 4, 5)
sn

array([[[ 1.02076273,  0.20597276,  0.34296685,  0.06325892,
         -0.64682799],
        [ 0.71037105,  0.7009931 ,  0.52084524,  1.79255787,
         -0.98929358],
        [ 1.72517572,  0.14831693,  0.20965159,  0.94766804,
         -0.1998086 ],
        [-0.61060789, -0.83938528, -0.14739848, -0.98658448,
         -0.22032106]],

       [[-1.44002262,  0.0688055 ,  1.3688821 , -1.56581533,
          0.7488219 ],
        [ 0.10877887,  0.2615954 , -0.24147034,  1.0155297 ,
          0.78119876],
        [-0.53713704, -0.16114107, -1.32858886, -0.49416343,
          0.93268756],
        [-0.34860371, -0.27055736,  0.4311068 , -1.51318638,
          0.611949  ]],

       [[ 0.78405841,  0.92171414,  0.59880218, -0.12726546,
         -0.04959109],
        [-1.22454202, -1.52754538,  0.032805  , -1.15509459,
          1.00110231],
        [-1.15513622,  1.00861893, -1.55333824, -0.20730755,
         -1.20153694],
        [ 0.99485384,  0.71080526,  0.07542988, -0.28748051,
          1

In [36]:
b = np.random.randint(100, 200, (3, 4))
b

array([[180, 175, 104, 139],
       [150, 144, 118, 147],
       [111, 116, 163, 184]])

In [37]:
np.random.seed(10)
np.random.randint(100, 200, (3, 4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [38]:
# 使用同一个种子，可以发现生成结果是相同的
np.random.seed(10)
np.random.randint(100, 200, (3, 4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

<div id="point3_2"></div>
##### np.random的随机数函数（二）
<img src="images/15.png" align="left">

In [39]:
a = np.random.randint(100, 200, (3, 4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [40]:
# 原来的数组a改变了
np.random.shuffle(a)
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [41]:
a = np.random.randint(100, 200, (3, 4))
a

array([[125, 113, 192, 186],
       [130, 130, 189, 112],
       [165, 131, 157, 136]])

In [42]:
np.random.permutation(a)

array([[125, 113, 192, 186],
       [130, 130, 189, 112],
       [165, 131, 157, 136]])

In [43]:
# 使用permutation乱序数组时，不会改变原来的数组a
a

array([[125, 113, 192, 186],
       [130, 130, 189, 112],
       [165, 131, 157, 136]])

<div id="point3_3"></div>
##### np.random的随机数函数（三）
<img src="images/16.png" align="left">

In [44]:
u = np.random.uniform(0, 10, (3,4))
u

array([[6.01038953, 8.05223197, 5.21647152, 9.08648881],
       [3.19236089, 0.90459349, 3.00700057, 1.13984362],
       [8.28681326, 0.46896319, 6.26287148, 5.47586156]])

In [45]:
n = np.random.normal(0, 1, (3,3))
n

array([[-0.49561818,  0.52563742, -0.38964647],
       [ 0.9372965 , -0.8169742 ,  1.01961544],
       [-0.34143633,  0.7512814 , -0.36225179]])

In [46]:
p = np.random.poisson(0.5, (3, 3))
p

array([[0, 1, 0],
       [2, 1, 0],
       [1, 0, 0]])

<div id="point4"></div>
### Numpy的统计函数

<div id="point4_1"></div>
##### numpy统计函数（一）
<img src="images/17.png" align="left">

In [47]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
np.sum(a)

105

In [49]:
np.mean(a, axis=1)

array([ 2.,  7., 12.])

In [50]:
np.mean(a, axis=0)

array([5., 6., 7., 8., 9.])

In [51]:
np.average(a, axis=0, weights=[10, 5, 1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [52]:
np.std(a)

4.320493798938574

In [53]:
np.var(a)

18.666666666666668

<div id="point4_2"></div>
##### numpy统计函数（二）
<img src="images/18.png" align="left">

In [54]:
b = np.arange(15, 0, -1).reshape(3, 5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [55]:
np.max(b)

15

In [56]:
np.min(b)

1

In [57]:
np.argmax(b)

0

In [58]:
# 生成多维下标
np.unravel_index(np.argmax(b), b.shape)

(0, 0)

In [59]:
np.ptp(b)

14

In [60]:
np.median(b)

8.0

<div id="point5"></div>
<div id="point5_1"></div>
### numpy的梯度函数
<img src="images/19.png" align="left">

In [61]:
a = np.random.randint(0, 20, (5))
a

array([18,  3, 16, 18, 16])

In [62]:
np.gradient(a)

array([-15. ,  -1. ,   7.5,   0. ,  -2. ])

In [63]:
b = np.random.randint(0, 50,(3, 5))
b

array([[14, 15, 17, 25, 46],
       [48, 42, 17, 32, 17],
       [41, 16, 41, 26, 12]])

In [64]:
np.gradient(b)

[array([[ 34. ,  27. ,   0. ,   7. , -29. ],
        [ 13.5,   0.5,  12. ,   0.5, -17. ],
        [ -7. , -26. ,  24. ,  -6. ,  -5. ]]),
 array([[  1. ,   1.5,   5. ,  14.5,  21. ],
        [ -6. , -15.5,  -5. ,   0. , -15. ],
        [-25. ,   0. ,   5. , -14.5, -14. ]])]